### PR TITLE
Refactor, add more pure functions and a screenshot

### PR DESCRIPTION
**Pull request by Wilfred**
* Various minor code refactorings.
* Allow any function that the byte compiler considers to be safe.
* Add a screenshot.

See the individual commits for more details.

### CODE REVIEW

**Comment by Fuco1** [comment]
Thanks, I'll try to review these ASAP.

FYI there's also a follow-up project (which will one day replace this repo probably) https://github.com/Fuco1/blablabla It has a silly name so people won't be too bothered about it.  It is much better than the solution here.  So if you want to use this for something serious that might give better results.

It's usable but the UI isn't very polished yet.

**Comment by Wilfred** [comment]
Neat, OK. So rather than re-evalling bits of the code, blablabla is modifying the functions to spy on them as values flow through? That makes a lot more sense.

**Comment by Fuco1** [comment]
Yea exactly.  It works almost exactly like `edebug` except it doesn't pause the evaluation.  This saves us a lot of trouble with evaluation rules as it simply follows whatever the Emacs interpreter does.

I've just tried it and loading the file then enabling `litable-mode` seems to work.  So it is semi-usable already.

**Comment by Fuco1** [comment]
I rebased this and merged it manually, thanks for the contributions!

**Pull request closed without merging**
